# Generated by Django 4.2.1 on 2023-05-24 03:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('customer_id', models.CharField(max_length=255)),
                ('router', models.CharField(choices=[('RED', 'red_light'), ('GREEN', 'green_light'), ('OTHER', 'other')], default='RED', max_length=255)),
                ('phone_number', models.IntegerField()),
                ('house_number', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('street', models.CharField(max_length=255)),
                ('near_street', models.CharField(max_length=255)),
                ('ward', models.CharField(max_length=255)),
                ('township', models.CharField(choices=[('NORTH DAGON', 'north dagon'), ('SOUTH DAGON', 'south dagon'), ('EAST DAGON', 'east dagon'), ('NORTH OAKALAPA', 'north oakalapa'), ('SOUTH OAKALAPA', 'south oakalapa'), ('THINGANGYUN', 'thingangyun'), ('HLAING', 'hlaing'), ('MINGALADONE', 'mingaladone'), ('THAKETA', 'thaketa'), ('DAWBON', 'dawbon'), ('MAYANGONE', 'mayangone'), ('SHWEPAUKKAN', 'shwepaukkan'), ('YANKIN', 'yankin'), ('INSEIN', 'insein'), ('OTHER', 'other')], default='EAST DAGON', max_length=255)),
                ('latlong', models.IntegerField()),
                ('comment', models.TextField()),
                ('create_at', models.DateField(default=django.utils.timezone.now)),
                ('update_at', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Internetplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('15mbps', '15Mbps'), ('25mbps', '25Mbps'), ('35mbps', '35Mbps'), ('55mbps', '55Mbps'), ('75mbps', '75Mbps'), ('95mbps', '95Mbps')], default='15Mbps', max_length=100)),
                ('price', models.CharField(choices=[('28,500', '28,500MMks'), ('36,000', '36,000MMks'), ('52,000', '52,000MMks'), ('72,000', '72,000MMks'), ('92,000', '92,000MMks'), ('122,000', '122,000MMks')], default='28,500', max_length=100)),
                ('create_date', models.DateField(default=django.utils.timezone.now)),
                ('update_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='NewInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('house_number', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('street', models.CharField(max_length=255)),
                ('ward', models.CharField(max_length=255)),
                ('township', models.CharField(choices=[('NORTH DAGON', 'north dagon'), ('SOUTH DAGON', 'south dagon'), ('EAST DAGON', 'east dagon'), ('NORTH OAKALAPA', 'north oakalapa'), ('SOUTH OAKALAPA', 'south oakalapa'), ('THINGANGYUN', 'thingangyun'), ('HLAING', 'hlaing'), ('MINGALADONE', 'mingaladone'), ('THAKETA', 'thaketa'), ('DAWBON', 'dawbon'), ('MAYANGONE', 'mayangone'), ('SHWEPAUKKAN', 'shwepaukkan'), ('YANKIN', 'yankin'), ('INSEIN', 'insein'), ('OTHER', 'other')], default='EAST DAGON', max_length=255)),
                ('latlong', models.IntegerField()),
                ('about', models.TextField()),
                ('create_at', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
