# Generated by Django 4.2.1 on 2023-05-24 03:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('customer_id', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='img/upload')),
                ('remark', models.TextField()),
                ('create_at', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
