# Generated by Django 4.2.1 on 2023-05-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_billing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='image',
        ),
        migrations.AddField(
            model_name='billing',
            name='bill_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='img/upload'),
        ),
    ]
