# Generated by Django 4.2.1 on 2023-05-24 07:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_billing_image_billing_bill_screenshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billingstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_status', models.BooleanField(default=False)),
                ('pending_status', models.BooleanField(default=False)),
                ('finishing_status', models.BooleanField(default=False)),
                ('create_at', models.DateField(default=django.utils.timezone.now)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.billing')),
            ],
        ),
    ]
