# Generated by Django 4.2.1 on 2023-05-25 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_newinstallationstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='update_at',
        ),
    ]
