# Generated by Django 4.2.1 on 2023-05-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_remove_complain_update_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='complain',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='complain',
            name='latlong',
        ),
        migrations.RemoveField(
            model_name='complain',
            name='near_street',
        ),
        migrations.RemoveField(
            model_name='complain',
            name='street',
        ),
        migrations.RemoveField(
            model_name='complain',
            name='township',
        ),
        migrations.RemoveField(
            model_name='complain',
            name='ward',
        ),
        migrations.AddField(
            model_name='complain',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='complain',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='complain',
            name='phone_number',
            field=models.IntegerField(blank=True),
        ),
    ]
