# Generated by Django 4.2.1 on 2023-05-25 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_remove_newinstallation_floor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='remark',
        ),
    ]
