# Generated by Django 4.2.1 on 2023-05-25 17:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_remove_billing_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingstatus',
            name='remark',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingstatus',
            name='update_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
