# Generated by Django 4.2.1 on 2023-05-25 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_billingstatus_remark_billingstatus_update_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingstatus',
            name='create_at',
        ),
    ]
