# Generated by Django 4.2.1 on 2023-05-25 19:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_remove_billingstatus_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingstatus',
            name='create_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
