# Generated by Django 4.2.1 on 2023-05-26 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_billingstatus_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingstatus',
            name='customer_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
