# Generated by Django 4.2.1 on 2023-05-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_billingstatus_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingstatus',
            name='customer_id',
        ),
        migrations.AlterField(
            model_name='billingstatus',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='billingstatus',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
