# Generated by Django 4.2.1 on 2023-05-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_complainstatus_department_employee_billing_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='remark',
            field=models.TextField(blank=True),
        ),
    ]
