# Generated by Django 4.2.1 on 2023-05-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_alter_billing_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='bill_screenshot',
            field=models.ImageField(null=True, upload_to='img/upload'),
        ),
    ]
