# Generated by Django 4.2.1 on 2023-05-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_delete_department_delete_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='status',
            field=models.CharField(choices=[('Read', 'Read'), ('Unread', 'Unread')], default='Unread', max_length=100),
        ),
    ]
