# Generated by Django 4.2.1 on 2023-05-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_complain_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='status',
            field=models.CharField(choices=[('Read', 'Read'), ('Unread', 'Unread')], default='Unread', max_length=50),
        ),
    ]
